### ISSUE TITLE
menu items not displayed correctly

### ISSUE THREAD

**Issue by Shivangbhatnagar237** [Alexandrbig1/header-navigation-menu#1]
### Description:
Issue Overview:
The current state of the food website's menu is experiencing a CSS issue where menu items are not being displayed correctly. This issue needs to be addressed in order to ensure the website's menu functions and displays as expected.

### Screenshot:

<details>
<summary>Issue screenshot</summary>

![image](https://github.com/Alexandrbig1/header-navigation-menu/assets/47966497/8f78417a-eb7b-422f-a291-146b9cc2ccdb)

</details>

- [x] I'm willing to work on this issue

**Comment by Shivangbhatnagar237** [comment]
cc @Alexandrbig1

**Comment by Alexandrbig1** [comment]
Good job!
