### ISSUE TITLE
No CONTRIBUTION.md file

### ISSUE THREAD

**Issue by Learningcomputers777** [Alexandrbig1/header-navigation-menu#8]
Assign me this I will complete this.
Add hackoctober fest label

**Comment by Alexandrbig1** [comment]
Added. Thank you!

**Comment by Learningcomputers777** [comment]
I did not add the file and made the pull request. I was waiting for your response.

**Comment by Alexandrbig1** [comment]
Ok, that's fine, I just added label as you asked for. Thanks

**Comment by Learningcomputers777** [comment]
So you don't want those files in your repo.

**Comment by Alexandrbig1** [comment]
What do you mean?

**Comment by Learningcomputers777** [comment]
Do you not want to have a contributing and code of conduct file so that in the future it would be helpful if people would want to contribute to your project

**Comment by Alexandrbig1** [comment]
The project will be on my repos, and yes you can contribute if you see some scenarios that can be improved, you can do so... I'll be glad for you to join our project as well as others! Please, be welcome! I just added label hacktoberfest as you asked for, but you didn't contribute yet, if you'll want it please, be welcome!

**Comment by Learningcomputers777** [comment]
Adding of Code of conduct and contributing file is an improvement to the project because it makes it looks legit. And you have added the hackoctober fest but when I made the changes then I will send a pull request you have to merge it and then you have to close the issue.

**Comment by Alexandrbig1** [comment]
Alright, then when you decide to contribute i will. I just answer for you issue.

**Comment by Learningcomputers777** [comment]
What I am saying is if you reopen the issues I will do the needful and send the PR and you merge it

**Comment by Alexandrbig1** [comment]
DId it. Keep it up! Thanks

**Comment by Learningcomputers777** [comment]
And the code of conduct issue too
