### ISSUE TITLE
No CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by Learningcomputers777** [Alexandrbig1/header-navigation-menu#9]
Assign me this I would complete this.
Add hackoctober fest label and does this repository count under hackoctober fest

**Comment by Alexandrbig1** [comment]
Added. Thank you!

**Comment by Learningcomputers777** [comment]
I did not make the changes and sent the pull request

**Comment by Alexandrbig1** [comment]
Ok, but I added a hacktoberfest label
